### ISSUE TITLE
Support "File" mode for PUT and POST

### ISSUE THREAD

**Issue by francois-normandin** [vipm-io/HTTP-REST-Client#18]
HTTP Request.vi does not support the "File" input.

Current method: 
![image](https://user-images.githubusercontent.com/11728548/154201112-97c3ba51-1997-4cf5-8004-f93830a5636b.png)

Proposal: 
If "body" is a valid path, select the "File" polymorphic instance.
![image](https://user-images.githubusercontent.com/11728548/154201219-1f8e2a7b-ea64-4791-9c26-43b8d0a52e6e.png)

**Comment by francois-normandin** [comment]
#19 Pull request

**Comment by jimkring** [comment]
implemented in PR #19 and released in 2.0.0.32
