### ISSUE TITLE
"Problematic reply" in "Parse Status Line.vi"

### ISSUE THREAD

**Issue by McGeifer** [vipm-io/HTTP-REST-Client#20]
Hey!

I'm currently running into the problem that the status response code from an API request is not parsed correctly.
We get this response from the LabVIEWHTTPClient.lvlib:POSTMultipart.vi:

> HTTP/1.1 200 Connection established
> 
> HTTP/1.1 400 Bad Request
> Date: Mon, 01 Aug 2022 11:39:25 GMT
> Content-Type: application/json
> Content-Length: 47
> Connection: keep-alive
> Cache-Control: no-cache
> ....

Which is parsed incorrectly with return code 200 instead of 400. Extending the the current workaround for code 100 might not be the best solution. Maybe we should determine if there are two HTTP/x.x xxx return headers and if so just ignore the first one?

**Comment by francois-normandin** [comment]
Refactored the Parse Status Line method to support all codes as described above.

![image](https://github.com/vipm-io/HTTP-REST-Client/assets/11728548/2226a586-9100-46a6-a3d7-82a087896d91)

PR #32 to fix this issue
