### ISSUE TITLE
Request to rebuild against NI's new HTTP API when it is released. 

### ISSUE THREAD

**Issue by ChrisCilino** [vipm-io/HTTP-REST-Client#24]
The PostMultiPart VI wraps NI's [Post MultiPart](https://www.ni.com/docs/en-US/bundle/labview/page/lvcomm/http_client_postmultipart.html). Turns out that NI's shipping VI doesn't support HTTP 1.1 and there's no way to force it to use HTTP 1.1. This causes some servers to refuse the request. 
 
In the [Champions form](https://forums.ni.com/t5/LabVIEW-Champion-Discussions/HTTP-PostMultipart-Server-says-quot-HTTP-1-1-426-Upgrade/td-p/4257550) (@jimkring has access) Darren posted a new unreleased version of the HTTP library. 

This ticket is to release a new version of the REST API that links against the new version of the HTTP library soon to be released by NI. According to Darren, the library will support lv 2019 64 bit and forward.

**Comment by francois-normandin** [comment]
If this request is considered, may I suggest that the library remains in LV2013 but provide an overridable method to allow an extension path to HTTP 1.1 instead of an outright upgrade?

**Comment by ChrisCilino** [comment]
@francois-normandin I like your idea a lot. But when attempting to create a child, I ran into various problems scoping problems.  If these "internal" functions were protected, then children could use them.  So maybe this issue needs to be broken up into two issues
1. To relink against new NI lib when it arrives
2. Enable extension through inheritance. 
![image](https://user-images.githubusercontent.com/43503595/193419354-d7fc30d5-36ca-4ea1-8d09-4405874794cd.png)

**Comment by ChrisCilino** [comment]
@jimkring Looks like 2.0 is on the horizon! any chance this request was implemented?

**Comment by jimkring** [comment]
HI @ChrisCilino. I didn't implement it. If you make a Pull Request with code in 2020, we can help review/test the proposal.

**Comment by jimkring** [comment]
Also @francois-normandin -- this "add an override" idea would probably be addressed if we implemented a more general interface abstraction, as in PR #17.

**Comment by ChrisCilino** [comment]
@jimkring can you please help me understand why this was closed? I'm guessing that if #17 is solved then this issue would also be solved?

**Comment by jimkring** [comment]
Probably happened (closed) automatically/accidentally in the last comment

**Comment by francois-normandin** [comment]
@ChrisCilino I attached a proposed build in PR #28 , in case you'd like to give it a spin.

**Comment by ChrisCilino** [comment]
@jimkring any updates on pushing making another build that includes Francois' fix?

**Comment by jimkring** [comment]
PR #28 has been accepted/merged, so I'll close this one.
