### ISSUE TITLE
Assert_IsFile.vi hangs when passed large json body requests that are not files

### ISSUE THREAD

**Issue by ChrisCilino** [vipm-io/HTTP-REST-Client#25]
vi.lib\addons\_JKI.lib\REST Client\classes\REST Client\Assert_IsFile.vi
![image](https://github.com/vipm-io/HTTP-REST-Client/assets/43503595/1208af4b-e076-41ff-9c28-f1e5b1be679c)

The vi above takes in the body of a request to determine if it is a file path. The problem is that "String to Path" takes a very long time to execute for bodies that are large. I have a put request hat has over 1 million characters in it (json string publishing to a web page).  AND for reasons I don't understand, the String to Path returns the massive JSON string as a path!

Even worse, the "File or Folder Exists" hangs when the very large path is passed to it. 

So I'm going to have to revert to the previous release of the rest api. 

Recommended solutions
1. get string length. if larger than the OS max path length, this is not a path. (not sure if this will work for both windows and mac). 

In any event, an alternate algorithm is needed to determine if this string is a path or not.

**Comment by francois-normandin** [comment]
@ChrisCilino 
How about this? Limiting to 255 char is possible too. I set it to 4x arbitrarily.
It would break as soon as a XML or JSON char is found. We could extend to commas and other punctuations. 
Is there an (official) list of disallowed chars for filenames somewhere?

![image](https://github.com/vipm-io/HTTP-REST-Client/assets/11728548/21850cad-b79b-451c-b5ab-540debfead80)

**Comment by ChrisCilino** [comment]
@francois-normandin, You're the best!
1. I think the 1000 character limit makes sense. Might need to make that a class property in the future but I wouldn't bother for now.
2. Love breaking on XML or JSON! 
3. I'm not aware of a disallowed character list. And if there were it would be very os specific. And part of the problem would also be network paths. When I try to add an illegal character to a file name on windows I get the error below:
![image](https://github.com/vipm-io/HTTP-REST-Client/assets/43503595/2f45faad-daa5-4a3b-8236-be3084b3033c)

This post has some interesting information. 
https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names
But as I feared: "Note that the reserved DOS device names and the rule about filenames ending in a dot or spaces are applied by the runtime library when converting a DOS path to a native NT path. If a path starts with the "\\?\" local-device prefix, this normalization step gets skipped, except to replace "\\?\" with NT's "\??\" device prefix. This prefix instructs the object manager to search the logon-session and global DOS device directories for a symbolic link to a native NT device, which is usually a device object in the "\Device" directory."

So I think we'd have to allow question marks.

**Comment by francois-normandin** [comment]
Good idea to start at the end. We can then definitely limit to 255 chars + 1 for the delimiter.
I thought the native method to check for multiplatform filename would be good, but it does not start on the first fail, so I can only look for inspiration in there.

**Comment by ChrisCilino** [comment]
"I thought the native method to check for multiplatform filename would be good, but it does not start on the first fail, so I can only look for inspiration in there."

i'm not sure I understand what you mean here.

**Comment by francois-normandin** [comment]
Ha... I'm on my cell phone and auto correct for a bit in the way. I'll make more sense when I'm at the computer. @ChrisCilino 😁

**Comment by francois-normandin** [comment]
@ChrisCilino I give it more thought and I'm not convinced we should try to optimize for speed, and risk forgetting something. It is a REST call, which is probably not time critical down to the nanosecond.

I propose to cut-off at 4096 (longest Linux path allowed) and simply ensure it is an absolute path to proceed. We can let the "Check If File of Folder Exists" be responsible for the OS independence...

What do you think?

![image](https://github.com/vipm-io/HTTP-REST-Client/assets/11728548/21320ec1-3499-4197-a126-e364ffb9b535)

**Comment by ChrisCilino** [comment]
Hmmm..... if memeory serves, an empty path returns "true" from "file or folder exists" so I think what you've coded up will work in that case too since you are checking if the string is empty. 

Ship it!

**Comment by francois-normandin** [comment]
Indeed, it seemed redundant to add the verification in the second case structure since the first should find it, but just to be safe (in case of some weird non-printable or unicode chars in the body, I`ve added more usual checks on empty and not a path.

![image](https://github.com/vipm-io/HTTP-REST-Client/assets/11728548/1b1af588-eb77-410e-ac52-3dddae191291)

I'll do a pull request shortly!

**Comment by ChrisCilino** [comment]
happy to verify once the build is out!

**Comment by ChrisCilino** [comment]
@francois-normandin is there anything else I need to do on this or are we just waiting on a build from @jimkring ?

**Comment by grandangelo** [comment]
Hi guys, just ran into this issue. Do we know if a fix is foreseen? Or should I stick to previous versions?

**Comment by francois-normandin** [comment]
@grandangelo This link contains a non-released package with the fix:

https://github.com/vipm-io/HTTP-REST-Client/pull/28#issuecomment-1837557554

The pull request has not yet been accepted and released by JKI, so if you decide to use this unofficial release, please be diligent about managing the distribution on your machines as there is no guarantee that the next package released on vipm.io will be thev from the exact same source code/branch.

**Comment by ChrisCilino** [comment]
I really do wish JKI would release this fix. It's a shame that such a small and quick fix is gated by just rebuilding and releasing, and JKI hasn't yet simply rebuilt. We're now on month 7 of this issue. 
@grandangelo I don't know if you have direct connections into JKI, but I've done everything I can to voice my concern. If there's anything you can do to help, I'd be very appreciative.

**Comment by grandangelo** [comment]
@ChrisCilino, I've no connection with JKI, apart from having used their library sometimes...

I'm working on a software deployed on more than one hundred machines, with two other colleagues, I found easier to just add a README stating that we should stick to previous versions instead of internally managing a "different" package as suggested by @francois-normandin.

**Comment by ChrisCilino** [comment]
@grandangelo unfortunately that also has been my solution... royal bummer.

**Comment by jimkring** [comment]
Hi @grandangelo @francois-normandin @ChrisCilino,

The PR #28 has been accepted and a new release should be available on vipm.io. Thanks for your extended patience.
